- CMakeLists.txt
* ROCm Path Fix
* Installation Path Set
* Message print
> CMakeList Fixes

- CMakeLists.txt
- src/modules/cpu/host_fused_functions.hpp
Need to test with MIVisionX PR for tfr_update
> remove hack for mean and std AND remove BOOST static dependency

- .travis.yml
- Readme.md
- docker/rpp-on-ubuntu18.dockerfile
* Travis Failure - Fix
* Docker File - Ubuntu 18.04
> RPP Updates

- src/modules/hip/kernel/blend.hpp
- src/modules/hip/kernel/brightness.hpp
- src/modules/hip/kernel/gamma_correction.hpp
@rrawther @kiritigowda This is a minor PR that replicates the passing of vector strides mod (using uint2 / uint3 for strides). The PR makes the same change for the previous 3 tensor functions - brightness, blend, gamma_correction.
> Vector strides for hip kernels

- include/rppt_tensor_augmentations.h
- src/modules/hip/hip_tensor_augmentations.hpp
- src/modules/hip/kernel/dilate.hpp
- src/modules/hip/kernel/erode.hpp
- src/modules/rppt_tensor_augmentations.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-performancetests/HIP_NEW/generatePerformanceLogs.py
- utilities/rpp-performancetests/HIP_NEW/rawLogsGenScript.sh
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/testAllScript.sh
- Adds erode and dilate in tensor for hip
- Adds corresponding unit and performance tests
@asalmanp This PR contains tensor based optimized erode and dilate implementations for hip.
> Erode and Dilate - Tensor based optimization for hip

- include/rppdefs.h
- include/rppt_tensor_augmentations.h
- src/include/cpu/rpp_cpu_common.hpp
- src/include/cpu/rpp_cpu_simd.hpp
- src/include/hip/rpp_hip_common.hpp
- src/modules/cpu/host_tensor_augmentations.hpp
- src/modules/hip/hip_tensor_augmentations.hpp
- src/modules/hip/kernel/gridmask.hpp
- src/modules/rppt_tensor_augmentations.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-performancetests/HIP_NEW/generatePerformanceLogs.py
- utilities/rpp-performancetests/HIP_NEW/rawLogsGenScript.sh
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/rpp-performancetests/HOST_NEW/generatePerformanceLogs.py
- utilities/rpp-performancetests/HOST_NEW/rawLogsGenScript.sh
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/testAllScript.sh
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/rpp-unittests/HOST_NEW/testAllScript.sh
@rrawther @asalmanp This PR adds Gridmask to RPP.
- Adds gridmask augmentation on host and hip
- Adds the corresponding test suite on host and hip for both unit and performance tests
> Gridmask augmentation tensor implementation

- utilities/rpp-performancetests/HIP_NEW/BatchPD_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/BatchPD_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/BatchPD_hip_pln3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-performancetests/HOST_NEW/BatchPD_host_pkd3.cpp
- utilities/rpp-performancetests/HOST_NEW/BatchPD_host_pln1.cpp
- utilities/rpp-performancetests/HOST_NEW/BatchPD_host_pln3.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/rpp-performancetests/OCL_NEW/BatchPD_ocl_pkd3.cpp
- utilities/rpp-performancetests/OCL_NEW/BatchPD_ocl_pln1.cpp
- utilities/rpp-performancetests/OCL_NEW/BatchPD_ocl_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/BatchPD_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/BatchPD_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/BatchPD_hip_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-unittests/HOST_NEW/BatchPD_host_pkd3.cpp
- utilities/rpp-unittests/HOST_NEW/BatchPD_host_pln1.cpp
- utilities/rpp-unittests/HOST_NEW/BatchPD_host_pln3.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/rpp-unittests/OCL_NEW/BatchPD_ocl_pkd3.cpp
- utilities/rpp-unittests/OCL_NEW/BatchPD_ocl_pln1.cpp
- utilities/rpp-unittests/OCL_NEW/BatchPD_ocl_pln3.cpp
Adds the hipDeviceSynchronize() after all hip function calls.
> Test suite fix for batchPD HIP

- include/rppt_tensor_augmentations.h
- src/include/hip/rpp_hip_common.hpp
- src/modules/hip/hip_tensor_augmentations.hpp
- src/modules/hip/kernel/brightness.hpp
- src/modules/hip/kernel/color_twist.hpp
- src/modules/rppt_tensor_augmentations.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln3.cpp
Adds color twist tensor implementation for HIP
Adds corresponding unit and performance tests
> Color Twist Tensor for HIP

- CMakeLists.txt
- Readme.md
ReadME and CMake changes for build defaults
> RPP build defaults

- include/rppdefs.h
- include/rppt_tensor_effects_augmentations.h
- src/modules/hip/hip_tensor_effects_augmentations.hpp
- src/modules/hip/kernel/non_linear_blend.hpp
- src/modules/rppt_tensor_effects_augmentations.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
- Adds Non linear blend tensor implementation on HIP
- Adds relevant unit/perf tests
> Non linear blend Tensor impl - HIP

- CMakeLists.txt
> RPP - V 0.99 updates

- CHANGELOG.md
- CMakeLists.txt
- Readme.md
- docker/rpp-on-ubuntu20.dockerfile
- docker/rpp-on-ubuntu22.dockerfile
- utilities/rpp-performancetests/README.MD
- utilities/rpp-unittests/README.MD
* Radeon -> ROCm
* Docker Updates
* Link Updates
> RPP - Name Updates

- utilities/test_suite/README.md
New test_suite readme naming update
> Readme update for test_suite

- CHANGELOG.md
- Readme.md
* Changelog Updates
* Readme Updates
> RPP V-1.1.0

- .jenkins/common.groovy
run `enable scl` and `cmake` commands separately
> CI Fix for Centos7

- utilities/test_suite/HOST/Tensor_host.cpp
@kiritigowda @paveltc This is a one liner fix for output in unit test for lut host
> Lut unit test case fix

- src/modules/cl/handleocl.cpp
- src/modules/hip/handlehip.cpp
Fixes build fail on openCL @kiritigowda @LakshmiKumar23
> openCL build fix

- .jenkins/common.groovy
- README.md
* Jenkins SLES Update
* Readme - SLES build updates
> SLES - Fix

- docs/.sphinx/requirements.in
- docs/.sphinx/requirements.txt
- utilities/rpp-performancetests/HIP_NEW/uniqueFunctionalities_hip.cpp
- utilities/rpp-performancetests/HOST_NEW/uniqueFunctionalities_host.cpp
- utilities/rpp-unittests/HIP_NEW/uniqueFunctionalities_hip.cpp
- utilities/rpp-unittests/HOST_NEW/uniqueFunctionalities_host.cpp
Initial solution to update help for uniqueFunctionalities to precisely provide valid command lines
> Testing help update

- .jenkins/common.groovy
Make Test - tests added to Jenkins
> Jenkins - Add Test

- utilities/rpp-performancetests/HIP_NEW/uniqueFunctionalities_hip.cpp
- Made change to handle non supported bitdepths
> Uniquefunctionalities test suite fix

- include/rpp.h
- include/rppdefs.h
- include/rppt_tensor_color_augmentations.h
- include/rppt_tensor_data_exchange_operations.h
- include/rppt_tensor_effects_augmentations.h
- include/rppt_tensor_filter_augmentations.h
- include/rppt_tensor_geometric_augmentations.h
- include/rppt_tensor_morphological_operations.h
WIP:
- Adds support for Doxygen on RPP external API
> Documentation - RPP Doxygen support 

- .github/dependabot.yml
Have dependabot PRs target develop instead of master
> Set target for dependabot PRs to develop

- CMakeLists.txt
Proposed Changes:
- Enable ASAN Packaging (component based) 
- Add LICENSE file to RPP package
> ENABLE ASAN packaging RPP

- CMakeLists.txt
> ROCm Path - Options Added

- CMakeLists.txt
- utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
- utilities/rpp-unittests/HOST_NEW/CMakeLists.txt
- utilities/rpp-unittests/OCL_NEW/CMakeLists.txt
- utilities/test_suite/CMakeLists.txt
- utilities/test_suite/HIP/CMakeLists.txt
- utilities/test_suite/HIP/Tensor_hip.cpp
- utilities/test_suite/HIP/runTests.py
- utilities/test_suite/HIP/testAllScript.sh
- utilities/test_suite/HOST/CMakeLists.txt
- utilities/test_suite/HOST/Tensor_host.cpp
- utilities/test_suite/HOST/runTests.py
- utilities/test_suite/HOST/testAllScript.sh
- utilities/test_suite/rpp_test_suite_common.h
> CTest - RPP Test Suite

- CMakeLists.txt
- README.md
- cmake/FindHALF.cmake
Half used in project without checking install. This PR fixes the find half issue.
> Find - Half added

- .jenkins/common.groovy
- CHANGELOG.md
- CMakeLists.txt
Proposed Changes:
- Enable ASAN Packaging (component based split for dev, runtime and asan)
- Add LICENSE file to RPP package
- Cherry Pick Changes 056632e5367b81b102aa52acb2162b7f12de46df, 6445456e5e0c2aeba5e7832f455795b7000f8308, 0be915d2423280f06237bbaf27fe141e6f0d0e8c, 0a79f85308d260f0ce39d9178130a6ceaab7f25e, 9686f177258baf117f5a88e6b82d9418a862c0a3
from https://github.com/GPUOpen-ProfessionalCompute-Libraries/rpp/pull/235/commits
> Hot Fix - Changes for RPP ASAN, License file pkging

- src/modules/hip/kernel/tensor_sum.hpp
@kiritigowda This is a minor PR to add naming convention changes to the tensor_sum HIP kernel.
> Minor naming convention fixes in HIP

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/issue_report.yml
Hello, this PR is introducing a new issue template for ROCm public repositories to make it easier for users to submit the details for issues and bugs. Problems pertaining to documentation or non-bug related, users have the ability to open a blank issue template to submit their report. 
Thank you,
Community Support Team (ML SW SDK)
> Adding issue template

- utilities/test_suite/HIP/runTests.py
- utilities/test_suite/HIP/runTests_voxel.py
- utilities/test_suite/HOST/runAudioTests.py
- utilities/test_suite/HOST/runTests.py
- utilities/test_suite/HOST/runTests_voxel.py
@kiritigowda This is a minor PR that changes output writes from testing to CWD.
> Testing - change output folder image writes, data dumps, performance result writes to CWD

- CMakeLists.txt
- docs/doxygen/Doxyfile
> Develop - Merge to master

- utilities/test_suite/README.md
@kiritigowda This is just a minor PR to update the test_suite ReadMe formatting, and fix indentations.
> RPP test_suite README update

- CMakeLists.txt
- cmake/FindHALF.cmake
* Fix package license 
* cleanup
> RPP - Package updates

- include/rppdefs.h
- include/rppt_tensor_audio_augmentations.h
- src/modules/cpu/kernel/pre_emphasis_filter.hpp
- src/modules/cpu/kernel/spectrogram.hpp
- src/modules/rppt_tensor_audio_augmentations.cpp
- utilities/test_suite/HOST/Tensor_audio_host.cpp
@kiritigowda This PR needs to be merged into develop. Its got some merge fixes and minor latest changes.
- fix on api for spectrogram and relevant changes in test suite
- fix for preemphasis filter
> Audio support merge commit fixes 

- CMakeLists.txt
- docker/rpp-on-ubuntu20.dockerfile
- docker/rpp-on-ubuntu22.dockerfile
- Update Dockerfiles to take rocm6.1
- Remove advance AMD option in CmakeLists
> Docker updates

- .azuredevops/rocm-ci.yml
For build triggers in public-facing CI project on Azure Pipelines: https://dev.azure.com/ROCm-CI/ROCm-CI/_build
> Enable external CI pipeline triggers

- utilities/test_suite/HIP/Tensor_hip.cpp
- utilities/test_suite/HOST/Tensor_host.cpp
@rrawther @kiritigowda This is a very minor 2 files changed PR to just add gaussian/shot/snp noise to the new test suite.
No changes in library code, only test suite.
> RPP Test suite minor addition - gaussian/shot/snp noise

- CMakeLists.txt
- README.md
Fixes - #374 
```
root@simon:~/rpp-test# ctest    
Test project /root/rpp-test
Start 1: rpp_qa_tests_tensor_host_all
1/2 Test #1: rpp_qa_tests_tensor_host_all .....   Passed   23.60 sec
Start 2: rpp_qa_tests_tensor_hip_all
2/2 Test #2: rpp_qa_tests_tensor_hip_all ......   Passed  117.87 sec
100% tests passed, 0 tests failed out of 2
Total Test time (real) = 141.48 sec
```
> Test Package - Add clang for test compile

- docs/doxygen/Doxyfile
Add STRIP_FROM_PATH to present clean include file names
> remove include file paths

- include/rppt_tensor_arithmetic_operations.h
- include/rppt_tensor_audio_augmentations.h
- include/rppt_tensor_logical_operations.h
@kiritigowda @randyh62 Adds fix in RPP headers for docs not showing newer arithmetic, logical, audio groups
> Doxygen docs fix

- CMakeLists.txt
- src/modules/cpu/kernel/glitch.hpp
- Change two AVX instructions to ensure build on MacOS
> Build fix for MacOS

- CHANGELOG.md
Two for versions
Three for notes (changes, additions, etc)
> Fix header levels in changelog

- utilities/test_suite/README.md
@LakshmiKumar23 This PR adds mention of pandas as a pre-requisite for the RPP test suite
> Test Suite Readme update - pandas prerequisite

- src/modules/rppt_tensor_effects_augmentations.cpp
- Fixes memory access fault issue for pixelate HIP kernel
> RPP Bug Fix for pixelate HIP

- docs/sphinx/requirements.in
- docs/sphinx/requirements.txt
- include/rppt_tensor_effects_augmentations.h
- include/rppt_tensor_geometric_augmentations.h
- src/modules/rppt_tensor_effects_augmentations.cpp
> Test Suite fix - Update augmentation maps

- CHANGELOG.md
- CMakeLists.txt
- README.md
- include/rpp_version.h
> ROCm 6.3.0 - updates

- utilities/test_suite/common.py
> Test Suite - Minor bugfix

- src/modules/cpu/kernel/normalize.hpp
Adds bugfix to match generic kernel output to golden output for normalize
> Bugfix - RPP normalize generic

- README.md
- docs/install/install.rst
> Readme - updates

- .jenkins/common.groovy
- cmake/FindStdFilesystem.cmake
- utilities/test_suite/HIP/CMakeLists.txt
- utilities/test_suite/HOST/CMakeLists.txt
Package - remove log archive
Test - Run test from installed dir
> Jenkins - Fix Test

- CMakeLists.txt
- utilities/test_suite/README.md
Test package to bring most of it's dependencies
> Test Package - Updates

- src/modules/cl/handleocl.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/test_suite/HIP/Tensor_image_hip.cpp
- utilities/test_suite/HIP/Tensor_misc_hip.cpp
- utilities/test_suite/HOST/Tensor_image_host.cpp
- utilities/test_suite/HOST/Tensor_misc_host.cpp
> Deprecation fix - sprintf to snprintf

- src/include/cpu/rpp_cpu_common.hpp
- src/include/cpu/rpp_cpu_filter.hpp
- src/include/cpu/rpp_cpu_simd.hpp
- src/modules/cpu/kernel/glitch.hpp
Fix all SIMD instruction related issues encountered specifically with g++ compiler for RPP.
> RPP g++ build fix

- CHANGELOG.md
- CMakeLists.txt
- docs/sphinx/requirements.in
- docs/sphinx/requirements.txt
- src/include/cpu/rpp_cpu_common.hpp
- src/include/cpu/rpp_cpu_filter.hpp
- src/include/cpu/rpp_cpu_simd.hpp
- src/modules/cpu/kernel/glitch.hpp
* Fix package issue - RPM test package in RHEL 8.X missing key components
* Compiler - warnings and bug fix
* Docs - env updates
> ROCm 6.4: Cherrypick 

- src/include/common/cpu/rpp_cpu_batchpd.hpp
- src/modules/tensor/cpu/kernel/resize.cpp
Adds g++ build fixes post RPP Restructure auto merge.
> Build fix on g++

- .jenkins/common.groovy
Use AMD Clang ++ for code coverage
> Jenkins - Fix CodeCov

- CHANGELOG.md
> CHANGELOG - ROCm 7 updates
