ROCm/rpp

- Readme.md
Boost's download service has changed from bintray.com to JFrog.
> ReadMe update

- utilities/rpp-performancetests/HIP_NEW/BatchPD_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/BatchPD_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/BatchPD_hip_pln3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-performancetests/HOST_NEW/BatchPD_host_pkd3.cpp
- utilities/rpp-performancetests/HOST_NEW/BatchPD_host_pln1.cpp
- utilities/rpp-performancetests/HOST_NEW/BatchPD_host_pln3.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/rpp-performancetests/OCL_NEW/BatchPD_ocl_pkd3.cpp
- utilities/rpp-performancetests/OCL_NEW/BatchPD_ocl_pln1.cpp
- utilities/rpp-performancetests/OCL_NEW/BatchPD_ocl_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/BatchPD_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/BatchPD_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/BatchPD_hip_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-unittests/HOST_NEW/BatchPD_host_pkd3.cpp
- utilities/rpp-unittests/HOST_NEW/BatchPD_host_pln1.cpp
- utilities/rpp-unittests/HOST_NEW/BatchPD_host_pln3.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/rpp-unittests/OCL_NEW/BatchPD_ocl_pkd3.cpp
- utilities/rpp-unittests/OCL_NEW/BatchPD_ocl_pln1.cpp
- utilities/rpp-unittests/OCL_NEW/BatchPD_ocl_pln3.cpp
@asalmanp @kiritigowda This is a minor common fix across all 30 test suite files for a "non-ascii" error.
To ensure no junk values are in the string, it adds a default assignment.
> Test suite non-ascii fix

- src/modules/rppt_tensor_augmentations.cpp
@rrawther This is a minor PR that removes the OCL_COMPILE flag for tensor versions of RPP, and reformats the API file.
> Tensor API - Remove OCL_COMPILE and reformat

- include/rppdefs.h
- include/rppt_tensor_geometric_augmentations.h
- src/include/hip/rpp_hip_common.hpp
- src/include/hip/rpp_hip_roi_conversion.hpp
- src/modules/hip/hip_tensor_geometric_augmentations.hpp
- src/modules/hip/kernel/warp_affine.hpp
- src/modules/rppt_tensor_geometric_augmentations.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-performancetests/HIP_NEW/generatePerformanceLogs.py
- utilities/rpp-performancetests/HIP_NEW/rawLogsGenScript.sh
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/testAllScript.sh
- Adds support for warp affine tensor on hip.
- Support for U8/F32/F16/I8, NCHW/NHWC/toggle, Bilinear/NearestNeighbor is added.
- Adds corresponding unit tests and performance tests.
> Warp Affine tensor HIP

- CHANGELOG.md
- CMakeLists.txt
* RPP V 0.93 Release Updates
*Changelog added
> Updates - Changelog & CMakeList

- Readme.md
- RPP uses OpenCV just for unit-testing purposes.
- The PR adds ReadMe mods to mention use of either OpenCV 3.x or 4.x to match the MIVisionX compatibility and gives the same install instructions from MIVisionX-setup.py
- Tested with installation of OpenCV 3.4.0 (no-change) or OpenCV 4.5.5 on rocm 5.1.1 docker from rocm DockerHub.
> ReadMe mods - OpenCV 3.x or 4.x to match MIVisionX compatibility

- include/rppdefs.h
- include/rppt_tensor_effects_augmentations.h
- src/include/cpu/rpp_cpu_common.hpp
- src/include/hip/rpp_hip_common.hpp
- src/modules/cpu/host_tensor_effects_augmentations.hpp
- src/modules/cpu/kernel/noise_salt_and_pepper.hpp
- src/modules/hip/hip_tensor_effects_augmentations.hpp
- src/modules/hip/kernel/noise_salt_and_pepper.hpp
- src/modules/rppt_tensor_effects_augmentations.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-performancetests/HIP_NEW/generatePerformanceLogs.py
- utilities/rpp-performancetests/HIP_NEW/rawLogsGenScript.sh
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/rpp-performancetests/HOST_NEW/rawLogsGenScript.sh
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
- utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
- utilities/rpp-unittests/HIP_NEW/testAllScript.sh
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln1.cpp
- utilities/rpp-unittests/HOST_NEW/Tensor_host_pln3.cpp
- utilities/rpp-unittests/HOST_NEW/testAllScript.sh
- Adds rpp support for salt and pepper noise tensor on hip and host.
- Introduces generic 4 and 8 element seed-streams and support to running xorwow on SSE and AVX2 generating a vector of 8 random float numbers in parallel per CPU thread.
- Support for U8/F32/F16/I8, NCHW/NHWC/toggle is added.
- Adds corresponding unit tests and performance tests.
> Salt and Pepper Noise Tensor implementation on host and hip

- src/include/cl/rpp_cl_common.hpp
- src/include/cpu/rpp_cpu_common.hpp
- src/include/cpu/rpp_cpu_simd.hpp
- src/include/hip/rpp_hip_common.hpp
@rrawther This PR just changes the return type of inline functions from RppStatus RPP_SUCCESS to void as discussed.
1. Change return type of inline functions from RppStatus to void
2. Remove the RPP_SUCCESS return statement for all these inline void functions
> Change return type of inline helpers from RppStatus to void

- src/modules/rppt_tensor_geometric_augmentations.cpp
Build on **MacOS**
```
cmake ../rpp 
-- Apple macOS Detected -- GPU Support turned OFF
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AMD Radeon Performance Primitives (RPP) Version -- 0.99
-- AMD RPP install path set to -- /usr/local
-- AMD RPP Backend set to -- CPU
-- AMD RPP Build Type -- Release
-- Found Boost: /usr/local/lib/cmake/Boost-1.81.0/BoostConfig.cmake (found version "1.81.0") found components: filesystem system 
-- Found OpenMP_CXX: -Xclang -fopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Performing Test …
```
> MacOS failure - Define MacOS Function

- CMakeLists.txt
* Set clang as default CXX Compiler
> Clang Issue Fix - Set clang as default CXX Compiler

- utilities/test_suite/rpp_test_suite_common.h
Fixes HOST passing / HIP failing issue in rpp test_suite. The issue was replicable on MI100 ubuntu 22.04 + rocm-5.6.0-11969 at compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:11969-ubuntu-22.04-stg2
HIP test passing:
@paveltc @LakshmiKumar23 @kiritigowda
> RPP test_suite/HIP build fix

- .github/dependabot.yml
- docs/.sphinx/requirements.in
- docs/.sphinx/requirements.txt
- docs/conf.py
resolves: dependabot configuration and documentation dependencies
Summary of proposed changes:
-  Adds noCI labels for dependabot PRs because Read the Docs CI is separate from Jenkins/Math CI
-  Update rocm-docs-core to version 0.18.4
> Update dependabot configuration and documentation dependencies

- .readthedocs.yaml
use build.os in the .readthedocs.yaml config
https://docs.readthedocs.io/en/stable/config-file/v2.html
build.image (which is what is currently used implicitly) will be deprecated in October 2023
> Update ReadtheDocs config

- .github/CODEOWNERS
- docs/.sphinx/requirements.in
- docs/.sphinx/requirements.txt
Adding code owners for documentation. Plan is to add mandatory reviews from this group of code owners to merge any documentation changes. The header directory is related to documentation and thus changes to that are also flagged for documentation review.
> Add codeowners for documentation

- src/include/hip/rpp_hip_common.hpp
- src/modules/hip/kernel/box_filter.hpp
- src/modules/hip/kernel/dilate.hpp
- src/modules/hip/kernel/erode.hpp
@rrawther @asalmanp This PR just replaces all _lds occurrences to Shared in RPP tensor functions.
Once the Gaussian Filter PR is merged, all Shared mem sizes will be changed to the preprocessor define for better readability.
> Replace all _lds occurrences to _smem

- src/modules/hip/kernel/blend.hpp
- src/modules/hip/kernel/box_filter.hpp
- src/modules/hip/kernel/brightness.hpp
- src/modules/hip/kernel/color_cast.hpp
- src/modules/hip/kernel/color_to_greyscale.hpp
- src/modules/hip/kernel/color_twist.hpp
- src/modules/hip/kernel/contrast.hpp
- src/modules/hip/kernel/copy.hpp
- src/modules/hip/kernel/crop.hpp
- src/modules/hip/kernel/crop_mirror_normalize.hpp
- src/modules/hip/kernel/dilate.hpp
- src/modules/hip/kernel/erode.hpp
- src/modules/hip/kernel/exposure.hpp
- src/modules/hip/kernel/flip.hpp
- src/modules/hip/kernel/gamma_correction.hpp
- src/modules/hip/kernel/gridmask.hpp
- src/modules/hip/kernel/lut.hpp
- src/modules/hip/kernel/noise_gaussian.hpp
- src/modules/hip/kernel/noise_salt_and_pepper.hpp
- src/modules/hip/kernel/noise_shot.hpp
- src/modules/hip/kernel/non_linear_blend.hpp
- src/modules/hip/kernel/resize.hpp
- src/modules/hip/kernel/resize_crop_mirror.hpp
- src/modules/hip/kernel/resize_mirror_normalize.hpp
- src/modules/hip/kernel/spatter.hpp
- src/modules/hip/kernel/swap_channels.hpp
- src/modules/hip/kernel/warp_affine.hpp
@rrawther All host tensor kernels are already named "_host_tensor". 
This PR changes all tensor hip kernels to be named "_hip_tensor".
> RPP Tensor HIP kernels rename - "_tensor" to "_hip_tensor"

- CMakeLists.txt
- utilities/test_suite/CMakeLists.txt
@kiritigowda This is a minor PR that removes the original rpp-unittests tests that were added.
And commenting out the repetitive independent tests that were running even after testing "all".
I have added a comment stating that once we add individual tests in the cmake, the "all" style can be commented and independent ones used.
> Remove testing older functionalities from CI

- docs/doxygen/Doxyfile
Removes doxygen header and footer
Adds custom styles as well as better styling for dark mode
> Use custom rocm-docs-core footer, header, and stylesheets for doxysphinx

- CMakeLists.txt
- src/modules/hip/kernel/histogram.cpp
> Build fix for ROCm 6.0.0 gfx942

- utilities/test_suite/HIP/Tensor_hip.cpp
- utilities/test_suite/HIP/Tensor_voxel_hip.cpp
- utilities/test_suite/HIP/runTests.py
- utilities/test_suite/HIP/runTests_voxel.py
- utilities/test_suite/HOST/Tensor_host.cpp
- utilities/test_suite/HOST/Tensor_host_audio.cpp
- utilities/test_suite/HOST/Tensor_voxel_host.cpp
- utilities/test_suite/HOST/runAudioTests.py
- utilities/test_suite/HOST/runTests.py
- utilities/test_suite/HOST/runTests_voxel.py
- utilities/test_suite/common.py
@kiritigowda This is a minor PR that touches only test suite files to copy code from one place to another to restructure it better. It also has some reduced printing as requested in #282 + formatting / code cleanup.
- Move the common code in python scripts to a separate python script for reusability
- Fix the issue with repetitive decoding in case of performance tests
- Fix the tabbing issue in Tensor_hip.cpp
- caseMin and caseMax based changes in image cpp files
- Changes to run only necessary bitdepths in case of qaMode
- Changes in python test suite to skip augmentations/case numbers which are not supported
> RPP Test Suite Upgrade 6 - Restructure common HIP/HOST code

- include/rppdefs.h
- src/modules/cl/handleocl.cpp
- src/modules/cpu/kernel/down_mixing.hpp
- src/modules/handlehost.cpp
- src/modules/hip/handlehip.cpp
- src/modules/hip/kernel/gaussian_filter.hpp
- src/modules/hip/kernel/spatter.hpp
- src/modules/hip/kernel/tensor_max.hpp
- src/modules/hip/kernel/tensor_min.hpp
- src/modules/hip/kernel/tensor_sum.hpp
- src/modules/hip/kernel/warp_affine.hpp
- src/modules/rppt_tensor_effects_augmentations.cpp
- src/modules/rppt_tensor_geometric_augmentations.cpp
For uniformity in naming and readability:
- Renames all instances of reused maskArr HIP buffer to scratchBufferHip
- Renames all instances of reused tempFloatmem HOST buffer to scratchBufferHost
> Scratch buffers rename for HOST and HIP

- src/modules/hip/hip_tensor_arithmetic_operations.hpp
- src/modules/hip/kernel/copy.hpp
- src/modules/hip/kernel/gamma_correction.hpp
- src/modules/hip/kernel/gaussian_filter.hpp
- src/modules/hip/kernel/noise_salt_and_pepper.hpp
- src/modules/hip/kernel/noise_shot.hpp
- src/modules/hip/kernel/ricap.hpp
- src/modules/hip/kernel/spatter.hpp
- src/modules/hip/kernel/warp_affine.hpp
- src/modules/hip/kernel/water.hpp
- src/modules/rppt_tensor_effects_augmentations.cpp
- utilities/test_suite/HIP/Tensor_hip.cpp
- utilities/test_suite/HIP/Tensor_voxel_hip.cpp
- utilities/test_suite/rpp_test_suite_common.h
This is a minor PR to add some HIP fixes to match-up tensor code for uniformity:
- Uses pre-allocated common scratchBufferHip everywhere in Tensor code for scratch HIP memory
- Uses CHECK_RETURN_STATUS everywhere to adhere to C++17 for hip
- Removes additional variable usage
> Minor common-fixes for HIP

- CMakeLists.txt
Removing find_package(HIP) call in CMakeLists.txt - its already present in L215
> Fixing HIP CMake issue

- CHANGELOG.md
Based on the CMakeLists.txt for each release branch (eg: https://github.com/ROCm/rpp/blob/release/rocm-rel-5.7/CMakeLists.txt)
Relates to https://github.com/ROCm/ROCm/issues/3431
> Add the ROCm version for each rpp release in the changelog

- utilities/test_suite/README.md
Addresses #416 and matches installation to Rocal
> Readme update - Turbojpeg dependency

- CMakeLists.txt
If the user has passed in the compiler to use for building, use it. Otherwise set it to clang++
On Fedora there is no /opt/rocm/llvm/bin/clang++, the compiler used is a system compiler wrapped by hipcc. So set COMPILER_FOR_HIP to llvm/bin/clang++ only if that file exists, otherwise use the CMAKE_CXX_COMPILER.
> Improve compiler setup

- docs/sphinx/requirements.in
- docs/sphinx/requirements.txt
bump rocm-docs-core to 1.6.2
also updates doc dep chain, including sphinx for `sphinx.util.display`
> Update documentation requirements (bump rocm-docs-core to 1.6.2)

- include/rppt_tensor_effects_augmentations.h
- include/rppt_tensor_geometric_augmentations.h
Broken images were generally named with .jpg suffix, while file names in data folder used .png suffix. One had the addition of img in the header file which was not found in the file name. 
Corrected the suffix and names in the header files.
> fix broken image links

- include/rppt_tensor_effects_augmentations.h
- include/rppt_tensor_geometric_augmentations.h
- include/rppt_tensor_statistical_operations.h
- Fix roiTensorSrc to roiTensorPtrSrc in the header files to ensure parameter name is same as documentation name and avoid Doxygen warnings
> Docs fix - Match parameter name in API and Docs

- include/rpp_version.h
- include/rppdefs.h
- src/include/cpu/rpp_cpu_common.hpp
- src/modules/hip/kernel/resample.hpp
- src/modules/rppt_tensor_audio_augmentations.cpp
- utilities/test_suite/HIP/Tensor_audio_hip.cpp
- utilities/test_suite/HOST/Tensor_audio_host.cpp
- utilities/test_suite/rpp_test_suite_audio.h
- Move out the windowed_sinc function from rppdefs.h and readded vector usage for lookup table for compatibility
- Disable the numDims validation for preemphasis HOST kernel temporarily
> MIVisionX compatibility fix - Resample and preemphasis filter

- .jenkins/common.groovy
- utilities/test_suite/README.md
- Fixes test suite build by locking to specific nifti_clib commit ID - https://github.com/NIFTI-Imaging/nifti_clib/commit/84e323cc3cbb749b6a3eeef861894e444cf7d788
- Minor change to sudo apt install half in common.groovy for jenkins
> Test suite build fix - Lock to specific 'nifti_clib' commit

- CMakeLists.txt
RPM - Some deps are not available on RHEL 9 - has to be manual install
> Test Package - Updates for RPM

- api/rpp.h
- src/include/common/binary_cache.hpp
- src/include/common/tmp_dir.hpp
The objective of the PR is to update the filesystem import in rpp.
Due to the recent changes in restructure PR related to Commit - [Remove filesystem.h file and consolidate in rpp.h](https://github.com/r-abishek/rpp/commit/bc2c36ebc5859ba027dca2c664bff9e449c0048c) the MIVisionX build started to fail
This issue is owing to the fact that MIVisionX for rpp dependencies uses CXX Standard 14 contrary to RPP that uses CXX 17 for compilation - https://github.com/ROCm/MIVisionX/blob/c166676dfe5e9bf1c356554a244bde4d7f4ebb8f/amd_openvx_extensions/amd_rpp/CMakeLists.txt#L25
Hence changes have been added to restore support for multiple CXX standards in this commit
> MIVisionX compatibility fix - Filesystem import updates
